# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpRIl7HzEnSAzeXeeL5ZPu6oQBBiARBl
"""

!pip install speechrecognition

!pip install gTTS speechrecognition pydub pyautogui
!pip install pyaudio
!pippwin install pyaudio

!pip install gTTS
!pip install gtts

import speech_recognition as sr
import webbrowser

r = sr.Recognizer()

with sr.Microphone() as source:
    print("Fale algo...")
    r.adjust_for_ambient_noise(source)
    audio = r.listen(source)

try:
    text = r.recognize_google(audio, language="pt-BR")
    print("Você disse:", text)

    if "youtube" in text.lower():
        webbrowser.open("https://www.youtube.com")
    elif "firefox" in text.lower():
        webbrowser.open("https://www.mozilla.org/firefox/")
    elif "google" in text.lower():
        webbrowser.open("https://www.google.com")
    elif "whatsapp" in text.lower():
        webbrowser.open("https://web.whatsapp.com")
    else:
        print("Comando não reconhecido.")

except sr.UnknownValueError:
    print("Não entendi o que você disse")
except sr.RequestError as e:
    print(f"Erro no serviço: {e}")